---
#============================================================================================================
# gitea
#============================================================================================================
# @todo update # update gitea binary data

# @var run_role_gitea: yes # flag used to disable this role
run_role_gitea: yes

# @vargitea_dir: "/opt/gitea" # installation location for gitea
gitea_dir: "/opt/gitea"
# @vargitea_data_dir: "/opt/gitea/data" # location for gitea data
gitea_data_dir: "/opt/gitea/data"

# @var gitea_bind_ip: "127.0.0.1" # ip address to listen to
gitea_bind_ip: "127.0.0.1"

# @var gitea_port: "3000" # port to listen to
gitea_port: "3000"

# @var gitea_db_type: "mysql" # database type: mysql or sqlite3
gitea_db_type: "mysql"
# @var gitea_user: gitea # system user
gitea_user: gitea
# @var gitea_db_user: gitea # mysql user and database name
gitea_db_user: gitea
# @var gitea_db_pass: "gitea" #mysql password
gitea_db_pass: "gitea"

# @var gitea_secret_key: "random"
gitea_secret_key: "random"

# @var gitea_domain: "localhost" # domain where gitea is installed, used for generating links
gitea_domain: "localhost"

# @var gitea_http_port: "" # if gitea is setup behind a proxy that is on a non standard port,
# change this to the termination port, used for url generation
gitea_http_port: ""

# @var gitea_version: 1.2.2 # current installation version
#gitea_version: 1.2.2
gitea_version: 1.7.3

# @var gitea_binary: "https://github.com/go-gitea/gitea/releases/download/v{{gitea_version}}/gitea-{{gitea_version}}-linux-amd64"
# current download dir for the current version
gitea_binary: "https://github.com/go-gitea/gitea/releases/download/v{{gitea_version}}/gitea-{{gitea_version}}-linux-amd64"


# @var gitea_sum: "2830d77004eb03865fa3860bfb4dd34ccd497070b6f6de667a7de97c3471e07d" # checksum of the current version
#gitea_sum: "2830d77004eb03865fa3860bfb4dd34ccd497070b6f6de667a7de97c3471e07d"
gitea_sum: "49b733a3272dc49cb869c1ba9624a9880168f27b8112197d0c7fa32411dbf625"

# @example upgrade: in order to upgrade to a newer gitea version you need to setup all 3 variables accordingly
#gitea_version: 1.2.3
#gitea_binary: "https://github.com/go-gitea/...."
#gitea_sum: "2830d77 ... de97c3471e07d"

# @var gitea_version_delete: ["1.1.0"] # dict of older versions that should be deleted
gitea_version_delete:
  - "1.1.0"
  - "1.2.2"
