---

- name: "Create htpasswd file"
  htpasswd:
    path:  "{{ webservices_root }}/{{ item.0.name }}/home_dir/{% if item.1.htpasswd_filename is defined and item.1.htpasswd_filename %}{{ item.1.htpasswd_filename }}{% else %}.htpasswd_{{ item.1.domain }}{% endif %}"
    name:         "{{ htpasswd.user }}"
    password:     "{{ htpasswd.pass }}"
    owner:        "{{ item.0.name }}"
    group:        "{{ webservices_group }}"
    mode:         0750
  with_items: " {{ item.1.htpasswd_file_users }} "
  loop_control:
    loop_var: htpasswd
  notify: "restart web server"
  when:
    - item.0.enabled | default (true)
    - item.0.nginx is defined
    - item.0.nginx.enabled | default (false,true)
    - item.1.authentication is defined
    - item.1.authentication | default (false,true)
    - htpasswd.enabled

- name: "Create htpasswd file"
  htpasswd:
    path:  "{{ webservices_root }}/{{ item.0.name }}/home_dir/{% if item.1.htpasswd_filename is defined and item.1.htpasswd_filename %}{{ item.1.htpasswd_filename }}{% else %}.htpasswd_{{ item.1.domain }}{% endif %}"
    name:         "{{ htpasswd.user }}"
    state: absent
  with_items: " {{ item.1.htpasswd_file_users }} "
  loop_control:
    loop_var: htpasswd
  notify: "restart web server"
  when:
    - item.0.enabled | default (true)
    - item.0.nginx is defined
    - item.0.nginx.enabled | default (false,true)
    - item.1.authentication is defined
    - item.1.authentication | default (false,true)
    - not htpasswd.enabled