---
#============================================================================================================
# BasicHosts
#============================================================================================================
basic_host_hostname: "ansible-autobott-linux-server-email"
#basic_host_fqdn:


